# .goreleaser.yml
# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: wait-for
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./wait-for.go
    binary: wait-for
archives:
  - id: nix
    ids:
      - wait-for
    formats:
      - tar.gz
    name_template: &name_template >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: windows
    ids:
      - wait-for
    formats:
      - zip
    name_template: *name_template
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    # remove commit messages that match these regexes
    exclude:
      - '^docs:'
      - '^test:'
      - 'merge'
      - 'Merge'
release:
  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false
  # If set to true, will mark the release as a pre-release.
  # Default is false.
  prerelease: "auto"

# modelines, see http://vimdoc.sourceforge.net/htmldoc/options.html
# vim:tabstop=2:shiftwidth=2:softtabstop=2:expandtab
