name: Go

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
      id: go

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build
      run: go build -v -o wait-for .

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: linux_amd64_binary
        path: ./wait-for
